### ISSUE TITLE
My humble advice

### ISSUE THREAD

**Issue by farhan511** [2Checkout/woocommerce#10]
Hi Guys, 
My humble advice is to avoid upgrading to convert plus, at least for a while if you want to keep sales normal during the holiday season.
This plugin has so many issues, especially it will change the whole payment structure of your site. even your previous customers who place daily orders using the same card will not be able to place orders most of the time.
just check the abandon cart ratio of your site since you have upgraded to convert plus, you will see pending payments order will be higher.
if you contact 2co support they will send this cause: "While making payment customer just initialized 3DS Secure step and never completed it.
If there is an issue with this 3DS Secure step, we recommend that you reach out to the banks in order to solve this issue."

Now how is this possible same clients same cards, same ips even same device who was buying easily completing 3DS before convert plus daily multiple times using the old 2checkout sale page for many years.

another issue: issue mentioned at https://github.com/2Checkout/woocommerce/issues/7 
why "product name is not shown in the payment?"
in transaction details and payment invoices, convert plus shows store name instead of product name customer is buying.
We got it fixed by writing a custom function which worked well for us.

another issue: The IPN Callback issue all of the other payment plugins showing the call back option in HTTPS but only this plugin is showing it in HTTP.

another issue: add 2 - 3 different products in cart, then only change to quantity of 1 product from 1x to 2x then go to checkout and go to convert plus to complete payment you will see convert plus will raise the order total price 2x by changing all products quantity 2x in the payment page

Even custom plugin provider https://wordpress.org/plugins/woocommerce-2checkout-payment/ 
They fix bugs more quickly than @craigchristenson but they are also struggling as we bought the pro version they was offering even paid service charges to fix the issue but they are also unable to deal with convert plus.

As we see many issues reported since November and still pending and we have to wait for @craigchristenson to make the next commit after the holidays.
we are now finding a way to revert back to the old version of the 2co woo plugin as we have already suffered huge losses by upgrading to convert plus.

**Comment by sagitaire123** [comment]
Hello @farhan511 
You're right, there's many problems with the convertplus.

I'm personally using 2Checkout Inline, and it seems working good without any problem, you can use temporary while @craigchristenson fix the convert plus.

Or maybe you have constraints to only use convertplus ?

**Comment by farhan511** [comment]
@sagitaire123 
Thanks for your participation.
issue https://github.com/2Checkout/woocommerce/issues/7 is also in the inline version I have just checked.

please confirm me at your site inline checkout, is that showing your store name or product title at the pointed place of inline payment form?
https://prnt.sc/w9htx6

**Comment by sagitaire123** [comment]
Hi @farhan511 it's showing store name.
That's the only problem on Inline version, the rest seems working good, no problem with the 3D secure or higher abandon cart ratio.

**Comment by farhan511** [comment]
This is due to security reasons as mentioned at line 427 in twocheckout-convert-plus/wc-twocheckout-convert-plus.php by @craigchristenson /**
		 * for safety reasons we only send one Item with the grand total and the Cart_id as ProductName (identifier)
		 * sending products order as ONE we dont have to calculate the total fee of the order (product price, tax, discounts etc)
		 *
		 * @return array
		 */

**Comment by sagitaire123** [comment]
@farhan511 i think he's right, because i remember on the old version of 2checkout plugin on Woocommerce, some client was able to change price before redirecting to 2checkout page to make the payment.
For example the product cost $40, they will change the request to $0.01 and they will make a payment, if you don't check the order on your 2checkout panel, you can deliver it.

**Comment by craigchristenson** [comment]
@farhan511 I am sorry for the issues that you are experiencing, the team has been busy working on a fix for the 2PayJS issues that have been reported. I will try to investigate each issue you reported here.

As for the first issue that you mention with 3DS and Convert Plus, this is likely outside of this plugin since all of this interaction occurs after the redirect but I would like to look into it further as I was unaware of any issue here. Please provide me with your 2CO ticket number and I will trace the transactions and figure out what happened. I believe that the previous version of 2CO that you are referring to uses our legacy checkout which uses the same 3DS integration but the interface that interacts with the 3DS redirect is different so if we have an issue with the Convert Plus interface we certainly need to get that solved. Please provide me with any additional feedback that you can here.

For the IPN URL displayed in the admin area, we will release a fix for this so that the protocol displays properly in the admin area in the next release. Please not that this does not affect the IPN functionality which will work fine on 'http' or 'https', it's just displaying a suggestion for the URL to setup. You just need to use the proper protocol for your site when setting up the IPN URL in your 2Checkout admin.

The pricing issue you reported I cannot replicate. The plugin passes in 1 single lineitem for the total amount so the amount charged should be correct. I attempted the scenario you mentioned but since we are using the order total, it is always correct for me. Is the issue that the total is incorrect or that you only see 1 lineitem with the total amount? Please let me know so that I can investigate. A situation where the total is incorrect is a critical issue that needs to be addressed immediately if thats what is happening.

I can assure you that we are working on addressing the issues that are opened and I appreciate your feedback,

**Comment by farhan511** [comment]
@craigchristenson 
Thanks for taking time during the holidays.
I wish you and your family Merry Christmas and a happy new year.

Ticket id is 5299592
There must be some issue as when I asked support I only gave them 2 - 3 orders to check payment failure issue.
At my end, I am manually checking every order so what I can see is it works sometimes and sometimes not for example sometimes it rejects. 
Yesterday there was an interesting issue one customer who was an old customer tried 2 - 3 times to place the order but did not succeed then he tried again after few hours order got placed then after 1 hour he tried to place a new order but it was failed this time. :)
1 line item is also an issue because using woocommerce type of platforms sometimes products have multiple and complex variations especially when multiple items in the cart for security reasons we can go with 1 line item but in different scenarios, this will keep causing different issues. i could be wrong about 1 line item as I don't have enough data to make and a decision either 1 line item is good or not.

Total is also incorrect, I am sending you the screen I recorded while testing on 1 client site, it clearly explains the incorrect total issue and which is serious.
https://www.loom.com/share/7d79d885ce2744bfb5966ae333668241
Thanks.

**Comment by craigchristenson** [comment]
Hey buddy I hope you have a good holiday too. I'll start looking into your tickets tomorrow on the 3DS issues with convert plus when we have some developers in that area available but I cannot replicate the issue where the total is incorrect. We use the order total provided by the WooCommerce order object `$order->get_total()` with a single lineitem specifically to avoid a scenario where an incorrect total can happen. Are you using any WooCommerce extension to modify the checkout or the order? Your video is returning a 404, maybe i did not get to it in time. Please let me know so I can look into it further.

**Comment by craigchristenson** [comment]
@farhan511 For the 3DS issues you are reporting please reopen your ticket with 2Checkout support if you would like further investigation. As for the incorrect order total issue are you able to provide any more information on how I can replicate? I was not able to replicate on your website.

**Comment by craigchristenson** [comment]
The IPN and order status issued have been resolved in the latest release 1.2.0. Please make sure that you setup your IPN URL again after installing as it has changed in version 1.2.0. If you are able to let us know how to replicate the order total issue in the future please let us know in a new report.
