### ISSUE TITLE
Editing cart content

### ISSUE THREAD

**Issue by Organd** [2Checkout/woocommerce#7]
Hello,
in inline card payment, there is an option "Editing cart content"
but its not working, when i click, i cannot change the quantity increase or decrease.
so what the point of this option?

Also why product name is not shown in the payment?

**Comment by ashik726** [comment]
Hi @Organd 

I agree with your question. So, @craigchristenson Please take care this issue.

**Comment by craigchristenson** [comment]
Once the order has been passed to 2Checkout the cart cannot be edited in the 2Checkout interface which is why this is disabled. The product name is not shown here because the plugin passes in 1 single lineitem for the total amount representing all products. We do this to insure that to total is correct rather than trying to break out all individual products, discounts, or shipping which may be edited by other plugins to recalculate the total. Would it be better if we passed the woocommerce cart identifier as the product name instead of the store name?

**Comment by craigchristenson** [comment]
Please let us know if you have any further feedback on this after installing the latest release.
